application: capword
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /html
  static_dir: static

- url: /javascripts
  static_dir: static/javascripts

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images

- url: /.*
  script: _go_app
